// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SIGESPROC.DataAccess;
using SIGESPROC.Entities.Entities;

#nullable disable

namespace SIGESPROC.DataAccess.Context
{
    public partial class SIGESPROCContext : DbContext
    {
        public SIGESPROCContext()
        {
        }

        public SIGESPROCContext(DbContextOptions<SIGESPROCContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbcolaboradores> tbcolaboradores { get; set; }
        public virtual DbSet<tbcolaboradores_por_sucursales> tbcolaboradores_por_sucursales { get; set; }
        public virtual DbSet<tbsucursales> tbsucursales { get; set; }
        public virtual DbSet<tbtransportistas> tbtransportistas { get; set; }
        public virtual DbSet<tbusers> tbusers { get; set; }
        public virtual DbSet<tbviajes> tbviajes { get; set; }
        public virtual DbSet<tbviajes_detalle> tbviajes_detalle { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<tbcolaboradores>(entity =>
            {
                entity.HasKey(e => e.cola_id)
                    .HasName("PK__tbcolabo__2F350A8CB4431086");

                entity.HasIndex(e => e.cola_email, "UQ__tbcolabo__6CBE687EF283577D")
                    .IsUnique();

                entity.Property(e => e.cola_apelllido)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.cola_email)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.cola_nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.cola_sexo)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.user_activo).HasDefaultValueSql("((1))");
            });

            modelBuilder.Entity<tbcolaboradores_por_sucursales>(entity =>
            {
                entity.HasKey(e => e.cosu_id)
                    .HasName("PK__tbcolabo__F2917714A603E0C7");

                entity.HasIndex(e => new { e.cola_id, e.sucu_id }, "UC_ColaboradorSucursal")
                    .IsUnique();

                entity.Property(e => e.cola_activo).HasDefaultValueSql("((1))");

                entity.Property(e => e.distancia_km).HasColumnType("decimal(5, 2)");

                entity.HasOne(d => d.cola)
                    .WithMany(p => p.tbcolaboradores_por_sucursales)
                    .HasForeignKey(d => d.cola_id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbcolaboradores");

                entity.HasOne(d => d.sucu)
                    .WithMany(p => p.tbcolaboradores_por_sucursales)
                    .HasForeignKey(d => d.sucu_id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbsucursales");
            });

            modelBuilder.Entity<tbsucursales>(entity =>
            {
                entity.HasKey(e => e.sucu_id)
                    .HasName("PK__tbsucurs__770F069A39BBDD5F");

                entity.Property(e => e.sucu_direccion)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.sucu_nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbtransportistas>(entity =>
            {
                entity.HasKey(e => e.trans_id)
                    .HasName("PK__tbtransp__438CAC183E13BE26");

                entity.Property(e => e.trans_activo).HasDefaultValueSql("((1))");

                entity.Property(e => e.trans_apellido)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.trans_nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.trans_tarifa_por_km).HasColumnType("decimal(10, 2)");
            });

            modelBuilder.Entity<tbusers>(entity =>
            {
                entity.HasKey(e => e.user_user_id)
                    .HasName("PK__tbusers__937E190978A63595");

                entity.HasIndex(e => e.user_username, "UQ__tbusers__94975AD5FD74BA88")
                    .IsUnique();

                entity.Property(e => e.user_password_hash)
                    .IsRequired()
                    .HasColumnType("text");

                entity.Property(e => e.user_role)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.user_username)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.cola)
                    .WithMany(p => p.tbusers)
                    .HasForeignKey(d => d.cola_id)
                    .HasConstraintName("FK_tbusers_cola_id");
            });

            modelBuilder.Entity<tbviajes>(entity =>
            {
                entity.HasKey(e => e.viaj_id)
                    .HasName("PK__tbviajes__3C17BE54BC6F47D3");

                entity.Property(e => e.viaj_fecha).HasColumnType("date");

                entity.HasOne(d => d.sucu)
                    .WithMany(p => p.tbviajes)
                    .HasForeignKey(d => d.sucu_id)
                    .HasConstraintName("FK__tbviajes__sucu_i__498EEC8D");

                entity.HasOne(d => d.trans)
                    .WithMany(p => p.tbviajes)
                    .HasForeignKey(d => d.trans_id)
                    .HasConstraintName("FK__tbviajes__trans___4B7734FF");

                entity.HasOne(d => d.user_user)
                    .WithMany(p => p.tbviajes)
                    .HasForeignKey(d => d.user_user_id)
                    .HasConstraintName("FK__tbviajes__user_u__4A8310C6");
            });

            modelBuilder.Entity<tbviajes_detalle>(entity =>
            {
                entity.HasKey(e => e.vide_id)
                    .HasName("PK__tbviajes__08CD1EC585AA1FFA");

                entity.HasIndex(e => new { e.viaj_id, e.cola_id }, "UQ__tbviajes__EEE4EEFDA74EFEF8")
                    .IsUnique();

                entity.Property(e => e.distancia_km).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.total_a_pagar).HasColumnType("decimal(10, 2)");

                entity.HasOne(d => d.cola)
                    .WithMany(p => p.tbviajes_detalle)
                    .HasForeignKey(d => d.cola_id)
                    .HasConstraintName("FK__tbviajes___cola___51300E55");

                entity.HasOne(d => d.viaj)
                    .WithMany(p => p.tbviajes_detalle)
                    .HasForeignKey(d => d.viaj_id)
                    .HasConstraintName("FK__tbviajes___viaj___503BEA1C");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}