// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbcolaboradores_por_sucursales
    {
        public int cosu_id { get; set; }
        public int cola_id { get; set; }
        public bool? cola_activo { get; set; }
        public int sucu_id { get; set; }
        public decimal distancia_km { get; set; }

        public virtual tbcolaboradores cola { get; set; }
        public virtual tbsucursales sucu { get; set; }
    }
}