// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbcolaboradores
    {
        public tbcolaboradores()
        {
            tbcolaboradores_por_sucursales = new HashSet<tbcolaboradores_por_sucursales>();
            tbusers = new HashSet<tbusers>();
            tbviajes_detalle = new HashSet<tbviajes_detalle>();
        }

        public int cola_id { get; set; }
        public string cola_nombre { get; set; }
        public string cola_apelllido { get; set; }
        public string cola_sexo { get; set; }
        public string cola_email { get; set; }
        public bool? user_activo { get; set; }

        public virtual ICollection<tbcolaboradores_por_sucursales> tbcolaboradores_por_sucursales { get; set; }
        public virtual ICollection<tbusers> tbusers { get; set; }
        public virtual ICollection<tbviajes_detalle> tbviajes_detalle { get; set; }
    }
}