// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbsucursales
    {
        public tbsucursales()
        {
            tbcolaboradores_por_sucursales = new HashSet<tbcolaboradores_por_sucursales>();
            tbviajes = new HashSet<tbviajes>();
        }

        public int sucu_id { get; set; }
        public int TotalViajes { get; set; }
        public string sucu_nombre { get; set; }
        public string sucu_direccion { get; set; }
        

        public virtual ICollection<tbcolaboradores_por_sucursales> tbcolaboradores_por_sucursales { get; set; }
        public virtual ICollection<tbviajes> tbviajes { get; set; }
    }
}