// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbtransportistas
    {
        public tbtransportistas()
        {
            tbviajes = new HashSet<tbviajes>();
        }

        public int trans_id { get; set; }
        public string trans_nombre { get; set; }
        public string trans_apellido { get; set; }
        public decimal trans_tarifa_por_km { get; set; }
        public bool? trans_activo { get; set; }

        public virtual ICollection<tbviajes> tbviajes { get; set; }
    }
}