// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbusers
    {
        public tbusers()
        {
            tbviajes = new HashSet<tbviajes>();
        }

        public int user_user_id { get; set; }
        public string user_username { get; set; }
        public string user_password_hash { get; set; }
        public string user_role { get; set; }
        public int? cola_id { get; set; }

        public virtual tbcolaboradores cola { get; set; }
        public virtual ICollection<tbviajes> tbviajes { get; set; }
    }
}