// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbviajes_detalle
    {
        public int vide_id { get; set; }
        public int? viaj_id { get; set; }
        public int? cola_id { get; set; }
        public decimal distancia_km { get; set; }
        public decimal total_a_pagar { get; set; }

        public virtual tbcolaboradores cola { get; set; }
        public virtual tbviajes viaj { get; set; }
    }
}