// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbviajes
    {
        public tbviajes()
        {
            tbviajes_detalle = new HashSet<tbviajes_detalle>();
        }

        public int viaj_id { get; set; }
        public int? sucu_id { get; set; }
        public int? user_user_id { get; set; }
        public int? trans_id { get; set; }
        public DateTime viaj_fecha { get; set; }

        public virtual tbsucursales sucu { get; set; }
        public virtual tbtransportistas trans { get; set; }
        public virtual tbusers user_user { get; set; }
        public virtual ICollection<tbviajes_detalle> tbviajes_detalle { get; set; }
    }
}